/**
 * Bundled theme presets - used by Settings → Theme to swap the entire xterm
 * palette in one click, and applied on startup so the chrome (tabs, sidebar,
 * status bar) matches.
 *
 * Each preset has:
 *   - `theme`: the 12-color xterm palette + bright variants. Persisted to
 *     config.theme (existing schema) so xterm picks it up the same way as
 *     manual color edits.
 *   - `chrome`: overrides for the global :root CSS variables (background,
 *     borders, accent, etc). Applied via documentElement.style at runtime;
 *     not persisted - inferred from the active xterm theme each session.
 *
 * Adding a preset: append an object below. The detection logic in
 * applyChromeFromTheme matches presets by xterm color equality, so the
 * preset's `theme` must be unique enough to identify it.
 */
export interface ThemePreset {
  name: string;
  mode: 'dark' | 'light';
  theme: Record<string, string>;
  chrome: Record<string, string>;
}

const CATPPUCCIN_CHROME: Record<string, string> = {
  '--bg-primary': '#1e1e2e',
  '--bg-secondary': '#313244',
  '--border-color': '#45475a',
  '--focus-border': '#89b4fa',
  '--text-primary': '#cdd6f4',
  '--text-secondary': '#a6adc8',
  '--tab-bg': '#313244',
  '--tab-active': '#45475a',
  '--accent': '#89b4fa',
  '--accent-success': '#a6e3a1',
  '--accent-warning': '#f9e2af',
  '--accent-danger': '#f38ba8',
  '--rgb-accent': '137, 180, 250',
  '--rgb-accent-success': '166, 227, 161',
  '--rgb-accent-warning': '249, 226, 175',
  '--rgb-accent-danger': '243, 139, 168',
};

const WARM_DUSK_CHROME: Record<string, string> = {
  '--bg-primary': '#0a1422',           /* deeper navy so it's clearly not Catppuccin's purple-grey */
  '--bg-secondary': '#13202f',
  '--border-color': '#2a3a55',
  '--focus-border': '#ee6c4d',
  '--text-primary': '#d4dcec',
  '--text-secondary': '#8a96b0',
  '--tab-bg': '#13202f',
  '--tab-active': '#1f2c3e',
  '--accent': '#ee6c4d',
  '--accent-success': '#7ec1bb',
  '--accent-warning': '#f4a261',
  '--accent-danger': '#ff6b6b',
  '--rgb-accent': '238, 108, 77',
  '--rgb-accent-success': '126, 193, 187',
  '--rgb-accent-warning': '244, 162, 97',
  '--rgb-accent-danger': '255, 107, 107',
};

const TOKYO_NIGHT_CHROME: Record<string, string> = {
  '--bg-primary': '#1a1b26',
  '--bg-secondary': '#24283b',
  '--border-color': '#414868',
  '--focus-border': '#7aa2f7',
  '--text-primary': '#c0caf5',
  '--text-secondary': '#9aa5ce',
  '--tab-bg': '#24283b',
  '--tab-active': '#2f334d',
  '--accent': '#bb9af7',
  '--accent-success': '#9ece6a',
  '--accent-warning': '#e0af68',
  '--accent-danger': '#f7768e',
  '--rgb-accent': '187, 154, 247',
  '--rgb-accent-success': '158, 206, 106',
  '--rgb-accent-warning': '224, 175, 104',
  '--rgb-accent-danger': '247, 118, 142',
};

const DRACULA_CHROME: Record<string, string> = {
  '--bg-primary': '#282a36',
  '--bg-secondary': '#343746',
  '--border-color': '#44475a',
  '--focus-border': '#bd93f9',
  '--text-primary': '#f8f8f2',
  '--text-secondary': '#bd93f9',
  '--tab-bg': '#343746',
  '--tab-active': '#44475a',
  '--accent': '#ff79c6',
  '--accent-success': '#50fa7b',
  '--accent-warning': '#f1fa8c',
  '--accent-danger': '#ff5555',
  '--rgb-accent': '255, 121, 198',
  '--rgb-accent-success': '80, 250, 123',
  '--rgb-accent-warning': '241, 250, 140',
  '--rgb-accent-danger': '255, 85, 85',
};

const NORD_CHROME: Record<string, string> = {
  '--bg-primary': '#2e3440',
  '--bg-secondary': '#3b4252',
  '--border-color': '#4c566a',
  '--focus-border': '#88c0d0',
  '--text-primary': '#eceff4',
  '--text-secondary': '#d8dee9',
  '--tab-bg': '#3b4252',
  '--tab-active': '#434c5e',
  '--accent': '#88c0d0',
  '--accent-success': '#a3be8c',
  '--accent-warning': '#ebcb8b',
  '--accent-danger': '#bf616a',
  '--rgb-accent': '136, 192, 208',
  '--rgb-accent-success': '163, 190, 140',
  '--rgb-accent-warning': '235, 203, 139',
  '--rgb-accent-danger': '191, 97, 106',
};

const GRUVBOX_CHROME: Record<string, string> = {
  '--bg-primary': '#282828',
  '--bg-secondary': '#32302f',
  '--border-color': '#504945',
  '--focus-border': '#fabd2f',
  '--text-primary': '#ebdbb2',
  '--text-secondary': '#bdae93',
  '--tab-bg': '#32302f',
  '--tab-active': '#3c3836',
  '--accent': '#fe8019',
  '--accent-success': '#b8bb26',
  '--accent-warning': '#fabd2f',
  '--accent-danger': '#fb4934',
  '--rgb-accent': '254, 128, 25',
  '--rgb-accent-success': '184, 187, 38',
  '--rgb-accent-warning': '250, 189, 47',
  '--rgb-accent-danger': '251, 73, 52',
};

const ROSE_PINE_CHROME: Record<string, string> = {
  '--bg-primary': '#191724',
  '--bg-secondary': '#1f1d2e',
  '--border-color': '#403d52',
  '--focus-border': '#c4a7e7',
  '--text-primary': '#e0def4',
  '--text-secondary': '#908caa',
  '--tab-bg': '#1f1d2e',
  '--tab-active': '#26233a',
  '--accent': '#eb6f92',
  '--accent-success': '#9ccfd8',
  '--accent-warning': '#f6c177',
  '--accent-danger': '#eb6f92',
  '--rgb-accent': '235, 111, 146',
  '--rgb-accent-success': '156, 207, 216',
  '--rgb-accent-warning': '246, 193, 119',
  '--rgb-accent-danger': '235, 111, 146',
};

const SOLARIZED_DARK_CHROME: Record<string, string> = {
  '--bg-primary': '#002b36',
  '--bg-secondary': '#073642',
  '--border-color': '#586e75',
  '--focus-border': '#268bd2',
  '--text-primary': '#eee8d5',
  '--text-secondary': '#93a1a1',
  '--tab-bg': '#073642',
  '--tab-active': '#0a4452',
  '--accent': '#b58900',
  '--accent-success': '#859900',
  '--accent-warning': '#cb4b16',
  '--accent-danger': '#dc322f',
  '--rgb-accent': '181, 137, 0',
  '--rgb-accent-success': '133, 153, 0',
  '--rgb-accent-warning': '203, 75, 22',
  '--rgb-accent-danger': '220, 50, 47',
};

const SOLARIZED_LIGHT_CHROME: Record<string, string> = {
  '--bg-primary': '#fdf6e3',
  '--bg-secondary': '#eee8d5',
  '--border-color': '#93a1a1',
  '--focus-border': '#268bd2',
  '--text-primary': '#586e75',
  '--text-secondary': '#93a1a1',
  '--tab-bg': '#eee8d5',
  '--tab-active': '#fdf6e3',
  '--accent': '#268bd2',
  '--accent-success': '#859900',
  '--accent-warning': '#b58900',
  '--accent-danger': '#dc322f',
  '--rgb-accent': '38, 139, 210',
  '--rgb-accent-success': '133, 153, 0',
  '--rgb-accent-warning': '181, 137, 0',
  '--rgb-accent-danger': '220, 50, 47',
};

const CATPPUCCIN_LATTE_CHROME: Record<string, string> = {
  '--bg-primary': '#eff1f5',
  '--bg-secondary': '#e6e9ef',
  '--border-color': '#bcc0cc',
  '--focus-border': '#1e66f5',
  '--text-primary': '#4c4f69',
  '--text-secondary': '#6c6f85',
  '--tab-bg': '#e6e9ef',
  '--tab-active': '#dce0e8',
  '--accent': '#1e66f5',
  '--accent-success': '#40a02b',
  '--accent-warning': '#df8e1d',
  '--accent-danger': '#d20f39',
  '--rgb-accent': '30, 102, 245',
  '--rgb-accent-success': '64, 160, 43',
  '--rgb-accent-warning': '223, 142, 29',
  '--rgb-accent-danger': '210, 15, 57',
};

const ROSE_PINE_DAWN_CHROME: Record<string, string> = {
  '--bg-primary': '#faf4ed',
  '--bg-secondary': '#fffaf3',
  '--border-color': '#cecacd',
  '--focus-border': '#907aa9',
  '--text-primary': '#575279',
  '--text-secondary': '#797593',
  '--tab-bg': '#fffaf3',
  '--tab-active': '#f2e9e1',
  '--accent': '#b4637a',
  '--accent-success': '#56949f',
  '--accent-warning': '#ea9d34',
  '--accent-danger': '#b4637a',
  '--rgb-accent': '180, 99, 122',
  '--rgb-accent-success': '86, 148, 159',
  '--rgb-accent-warning': '234, 157, 52',
  '--rgb-accent-danger': '180, 99, 122',
};

const GITHUB_LIGHT_CHROME: Record<string, string> = {
  '--bg-primary': '#ffffff',
  '--bg-secondary': '#f6f8fa',
  '--border-color': '#d0d7de',
  '--focus-border': '#0969da',
  '--text-primary': '#1f2328',
  '--text-secondary': '#57606a',
  '--tab-bg': '#f6f8fa',
  '--tab-active': '#ffffff',
  '--accent': '#0969da',
  '--accent-success': '#1a7f37',
  '--accent-warning': '#9a6700',
  '--accent-danger': '#cf222e',
  '--rgb-accent': '9, 105, 218',
  '--rgb-accent-success': '26, 127, 55',
  '--rgb-accent-warning': '154, 103, 0',
  '--rgb-accent-danger': '207, 34, 46',
};

export const THEME_PRESETS: ThemePreset[] = [
  {
    name: 'Catppuccin Mocha',
    mode: 'dark',
    theme: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      cursor: '#f5e0dc',
      selectionBackground: '#585b70',
      black: '#45475a',
      red: '#f38ba8',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      blue: '#89b4fa',
      magenta: '#f5c2e7',
      cyan: '#94e2d5',
      white: '#bac2de',
      brightBlack: '#585b70',
      brightRed: '#f38ba8',
      brightGreen: '#a6e3a1',
      brightYellow: '#f9e2af',
      brightBlue: '#89b4fa',
      brightMagenta: '#f5c2e7',
      brightCyan: '#94e2d5',
      brightWhite: '#a6adc8',
    },
    chrome: CATPPUCCIN_CHROME,
  },
  {
    name: 'Warm Dusk',
    mode: 'dark',
    theme: {
      background: '#0a1422',
      foreground: '#d4dcec',
      cursor: '#ee6c4d',
      selectionBackground: '#2e3a52',
      black: '#2a3142',
      red: '#ee6c4d',
      green: '#7ec1bb',
      yellow: '#f4a261',
      blue: '#6c8ebf',
      magenta: '#d09cfa',
      cyan: '#56b6c2',
      white: '#d4dcec',
      brightBlack: '#3d4660',
      brightRed: '#ff8a6b',
      brightGreen: '#9bd6cf',
      brightYellow: '#ffb37a',
      brightBlue: '#8eaad6',
      brightMagenta: '#e0b3ff',
      brightCyan: '#7fc9d4',
      brightWhite: '#e0e8f5',
    },
    chrome: WARM_DUSK_CHROME,
  },
  {
    name: 'Tokyo Night',
    mode: 'dark',
    theme: {
      background: '#1a1b26',
      foreground: '#c0caf5',
      cursor: '#c0caf5',
      selectionBackground: '#33467c',
      black: '#15161e',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      magenta: '#bb9af7',
      cyan: '#7dcfff',
      white: '#a9b1d6',
      brightBlack: '#414868',
      brightRed: '#ff7a93',
      brightGreen: '#b9f27c',
      brightYellow: '#ff9e64',
      brightBlue: '#7da6ff',
      brightMagenta: '#bb9af7',
      brightCyan: '#0db9d7',
      brightWhite: '#c0caf5',
    },
    chrome: TOKYO_NIGHT_CHROME,
  },
  {
    name: 'Dracula',
    mode: 'dark',
    theme: {
      background: '#282a36',
      foreground: '#f8f8f2',
      cursor: '#f8f8f2',
      selectionBackground: '#44475a',
      black: '#21222c',
      red: '#ff5555',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      blue: '#bd93f9',
      magenta: '#ff79c6',
      cyan: '#8be9fd',
      white: '#f8f8f2',
      brightBlack: '#6272a4',
      brightRed: '#ff6e6e',
      brightGreen: '#69ff94',
      brightYellow: '#ffffa5',
      brightBlue: '#d6acff',
      brightMagenta: '#ff92df',
      brightCyan: '#a4ffff',
      brightWhite: '#ffffff',
    },
    chrome: DRACULA_CHROME,
  },
  {
    name: 'Nord',
    mode: 'dark',
    theme: {
      background: '#2e3440',
      foreground: '#eceff4',
      cursor: '#eceff4',
      selectionBackground: '#434c5e',
      black: '#3b4252',
      red: '#bf616a',
      green: '#a3be8c',
      yellow: '#ebcb8b',
      blue: '#81a1c1',
      magenta: '#b48ead',
      cyan: '#88c0d0',
      white: '#e5e9f0',
      brightBlack: '#4c566a',
      brightRed: '#bf616a',
      brightGreen: '#a3be8c',
      brightYellow: '#ebcb8b',
      brightBlue: '#81a1c1',
      brightMagenta: '#b48ead',
      brightCyan: '#8fbcbb',
      brightWhite: '#eceff4',
    },
    chrome: NORD_CHROME,
  },
  {
    name: 'Gruvbox Dark',
    mode: 'dark',
    theme: {
      background: '#282828',
      foreground: '#ebdbb2',
      cursor: '#ebdbb2',
      selectionBackground: '#504945',
      black: '#282828',
      red: '#cc241d',
      green: '#98971a',
      yellow: '#d79921',
      blue: '#458588',
      magenta: '#b16286',
      cyan: '#689d6a',
      white: '#a89984',
      brightBlack: '#928374',
      brightRed: '#fb4934',
      brightGreen: '#b8bb26',
      brightYellow: '#fabd2f',
      brightBlue: '#83a598',
      brightMagenta: '#d3869b',
      brightCyan: '#8ec07c',
      brightWhite: '#ebdbb2',
    },
    chrome: GRUVBOX_CHROME,
  },
  {
    name: 'Rosé Pine',
    mode: 'dark',
    theme: {
      background: '#191724',
      foreground: '#e0def4',
      cursor: '#e0def4',
      selectionBackground: '#403d52',
      black: '#26233a',
      red: '#eb6f92',
      green: '#31748f',
      yellow: '#f6c177',
      blue: '#9ccfd8',
      magenta: '#c4a7e7',
      cyan: '#ebbcba',
      white: '#e0def4',
      brightBlack: '#6e6a86',
      brightRed: '#eb6f92',
      brightGreen: '#31748f',
      brightYellow: '#f6c177',
      brightBlue: '#9ccfd8',
      brightMagenta: '#c4a7e7',
      brightCyan: '#ebbcba',
      brightWhite: '#e0def4',
    },
    chrome: ROSE_PINE_CHROME,
  },
  {
    name: 'Solarized Dark',
    mode: 'dark',
    theme: {
      background: '#002b36',
      foreground: '#eee8d5',
      cursor: '#eee8d5',
      selectionBackground: '#073642',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#586e75',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
    chrome: SOLARIZED_DARK_CHROME,
  },
  {
    name: 'Solarized Light',
    mode: 'light',
    theme: {
      background: '#fdf6e3',
      foreground: '#586e75',
      cursor: '#586e75',
      selectionBackground: '#eee8d5',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#002b36',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
    chrome: SOLARIZED_LIGHT_CHROME,
  },
  {
    name: 'Catppuccin Latte',
    mode: 'light',
    theme: {
      background: '#eff1f5',
      foreground: '#4c4f69',
      cursor: '#dc8a78',
      selectionBackground: '#bcc0cc',
      black: '#5c5f77',
      red: '#d20f39',
      green: '#40a02b',
      yellow: '#df8e1d',
      blue: '#1e66f5',
      magenta: '#ea76cb',
      cyan: '#179299',
      white: '#acb0be',
      brightBlack: '#6c6f85',
      brightRed: '#d20f39',
      brightGreen: '#40a02b',
      brightYellow: '#df8e1d',
      brightBlue: '#1e66f5',
      brightMagenta: '#ea76cb',
      brightCyan: '#179299',
      brightWhite: '#bcc0cc',
    },
    chrome: CATPPUCCIN_LATTE_CHROME,
  },
  {
    name: 'Rosé Pine Dawn',
    mode: 'light',
    theme: {
      background: '#faf4ed',
      foreground: '#575279',
      cursor: '#575279',
      selectionBackground: '#dfdad9',
      black: '#f2e9e1',
      red: '#b4637a',
      green: '#286983',
      yellow: '#ea9d34',
      blue: '#56949f',
      magenta: '#907aa9',
      cyan: '#d7827e',
      white: '#575279',
      brightBlack: '#9893a5',
      brightRed: '#b4637a',
      brightGreen: '#286983',
      brightYellow: '#ea9d34',
      brightBlue: '#56949f',
      brightMagenta: '#907aa9',
      brightCyan: '#d7827e',
      brightWhite: '#575279',
    },
    chrome: ROSE_PINE_DAWN_CHROME,
  },
  {
    name: 'GitHub Light',
    mode: 'light',
    theme: {
      background: '#ffffff',
      foreground: '#1f2328',
      cursor: '#1f2328',
      selectionBackground: '#d0d7de',
      black: '#24292f',
      red: '#cf222e',
      green: '#1a7f37',
      yellow: '#9a6700',
      blue: '#0969da',
      magenta: '#8250df',
      cyan: '#1b7c83',
      white: '#6e7781',
      brightBlack: '#57606a',
      brightRed: '#a40e26',
      brightGreen: '#116329',
      brightYellow: '#7d4e00',
      brightBlue: '#0550ae',
      brightMagenta: '#6639ba',
      brightCyan: '#0e6b6f',
      brightWhite: '#1f2328',
    },
    chrome: GITHUB_LIGHT_CHROME,
  },
];

export function themesEqual(
  a: Record<string, string> | undefined,
  b: Record<string, string>,
): boolean {
  if (!a) return false;
  for (const k of Object.keys(b)) {
    if ((a[k] || '').toLowerCase() !== (b[k] || '').toLowerCase()) return false;
  }
  return true;
}

/**
 * Match the current xterm theme to a preset by exact color equality and apply
 * its chrome to the document root. If no preset matches (user hand-edited
 * colors or migrated from an old config), fall back to Catppuccin Mocha.
 */
export function applyChromeFromTheme(theme: Record<string, string> | undefined): void {
  if (typeof document === 'undefined') return;
  const matched =
    THEME_PRESETS.find((p) => themesEqual(theme, p.theme)) ?? THEME_PRESETS[0];
  for (const [key, value] of Object.entries(matched.chrome)) {
    document.documentElement.style.setProperty(key, value);
  }
}
